# Generated by Django 3.2.18 on 2023-04-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0008_auto_20230428_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditnote',
            old_name='name',
            new_name='itemname',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='itemid',
            field=models.IntegerField(null=True),
        ),
    ]
