# Generated by Django 3.2.18 on 2023-05-15 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0010_creditnote_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote',
            name='date',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='hsn',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='itemid',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='itemname',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='price',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='total',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('itemname', models.CharField(max_length=255, null=True)),
                ('hsn', models.IntegerField(null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('customerlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.creditnote')),
            ],
        ),
    ]
