# Generated by Django 3.2.18 on 2023-04-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0006_creditnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='invoice_number',
            field=models.IntegerField(null=True),
        ),
    ]
