# Generated by Django 3.2.18 on 2023-04-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0007_creditnote_invoice_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item_details',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='hsn',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
